# Generated by Django 6.0.2 on 2026-03-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('family', 'Family member'), ('advocate', 'Advocate'), ('lawyer', 'Lawyer'), ('official', 'Government official'), ('journalist', 'Journalist'), ('reporter', 'Reporter/witness'), ('other', 'Other')], default='other', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('signal', models.CharField(blank=True, default='', max_length=50)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('persons', models.ManyToManyField(blank=True, related_name='contacts', to='cases.person')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
