# Generated by Django 6.0.2 on 2026-03-02 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseworkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('outreach', 'Outreach'), ('legal_filing', 'Legal filing'), ('media', 'Media engagement'), ('advocacy', 'Advocacy'), ('investigation', 'Investigation'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('done', 'Done')], default='open', max_length=20)),
                ('next_steps', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casework_performed', to=settings.AUTH_USER_MODEL)),
                ('persons', models.ManyToManyField(blank=True, related_name='casework_records', to='cases.person')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
