# Generated by Django 6.0 on 2026-09-02 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casework', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_email', models.BooleanField(default=True, help_text='Receive an email when casework events affect you.')),
                ('notify_inapp', models.BooleanField(default=True, help_text='Show in-app notifications in the bell.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('record_created', 'New casework record'), ('record_updated', 'Casework record updated'), ('status_done', 'Casework marked done'), ('record_seen', 'A peer opened this record')], max_length=24)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, help_text='When the email for this row was sent. NULL = not yet emailed.', null=True)),
                ('digest_key', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The user whose action caused this notification (often ≠ recipient).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_acted', to=settings.AUTH_USER_MODEL)),
                ('casework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='casework.caseworkrecord')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='casework_no_recipie_7d1af2_idx'), models.Index(fields=['recipient', 'emailed_at'], name='casework_no_recipie_0b015a_idx'), models.Index(fields=['casework', '-created_at'], name='casework_no_casewor_1429b3_idx')],
            },
        ),
    ]
