# Generated by Django 6.0.2 on 2026-03-02 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'case categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('edited', 'Edited'), ('deleted', 'Deleted')], max_length=20)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.IntegerField()),
                ('details', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('aliases', models.CharField(blank=True, default='', max_length=500)),
                ('country', models.CharField(max_length=100)),
                ('ethnicity', models.CharField(blank=True, default='', max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], default='', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('detained', 'Detained'), ('disappeared', 'Disappeared'), ('restricted_movement', 'Restricted Movement'), ('released', 'Released'), ('deceased', 'Deceased'), ('unknown', 'Unknown'), ('stateless', 'Stateless'), ('rights_restricted', 'Rights Restricted')], default='unknown', max_length=30)),
                ('medical_status', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('health_concerns', 'Health Concerns'), ('critical', 'Critical'), ('deceased', 'Deceased')], default='unknown', max_length=20)),
                ('medical_notes', models.TextField(blank=True, default='')),
                ('rough_location', models.CharField(blank=True, default='', help_text='Country/region level — shown publicly', max_length=255)),
                ('precise_location', models.CharField(blank=True, default='', help_text='City/address level — private by default', max_length=500)),
                ('last_known_date', models.DateField(blank=True, null=True)),
                ('summary_narrative', models.TextField(blank=True, default='')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('quality_tier', models.IntegerField(blank=True, choices=[(1, 'Tier 1 — Strong evidence'), (2, 'Tier 2 — Average evidence'), (3, 'Tier 3 — Weak evidence')], null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='cases.casecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'persons',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('firsthand', 'Firsthand'), ('secondhand', 'Secondhand'), ('news', 'News report'), ('document', 'Document')], default='firsthand', max_length=20)),
                ('source_attribution', models.CharField(blank=True, default='', help_text='Public attribution — e.g. "family member", "BBC report"', max_length=500)),
                ('reporter_name', models.CharField(blank=True, default='', max_length=255)),
                ('reporter_contact', models.TextField(blank=True, default='')),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, help_text='Leave blank for single-date events', null=True)),
                ('rough_location', models.CharField(blank=True, default='', max_length=255)),
                ('precise_location', models.CharField(blank=True, default='', max_length=500)),
                ('narrative', models.TextField()),
                ('suspected_reason', models.TextField(blank=True, default='', help_text='What family/source believes is the reason')),
                ('official_reason', models.TextField(blank=True, default='', help_text='What the state officially charged')),
                ('is_private', models.BooleanField(default=False, help_text='If true, entire report hidden from public view')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='cases.person')),
            ],
            options={
                'ordering': ['-date_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document'), ('video', 'Video'), ('link', 'External link')], default='photo', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted — authenticated users only'), ('sensitive', 'Sensitive — advocates/admin only')], default='public', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='cases.person')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='cases.report')),
            ],
            options={
                'verbose_name_plural': 'media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('spouse', 'Spouse'), ('other', 'Other relative')], max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_a', to='cases.person')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_b', to='cases.person')),
            ],
            options={
                'unique_together': {('person_a', 'person_b')},
            },
        ),
    ]
