# Generated by Django 6.0.2 on 2026-03-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='authoritative_source',
            field=models.CharField(blank=True, default='', help_text='Name of source database — e.g. "AAPP", "HRW", "shahit.biz"', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='authoritative_url',
            field=models.URLField(blank=True, default='', help_text='Link to this case in the original database', max_length=1000),
        ),
    ]
