# Generated by Django 6.0 on 2026-08-23 08:28

import cases.models
import cases.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_add_authoritative_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cases.storage.VisibilityRouterStorage(), upload_to=cases.models._media_upload_to),
        ),
    ]
