# Generated by Django 6.0 on 2026-09-05 12:43

import cases.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_perf_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'tiff', 'bmp', 'pdf', 'mp4', 'mov', 'webm']), cases.models._upload_size_validator]),
        ),
    ]
