# Generated by Django 6.0 on 2026-09-11 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_caseupdate_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=255)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_types', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True, default='')),
                ('narrative', models.TextField(blank=True, default='')),
                ('outcome', models.TextField(blank=True, default='')),
                ('source_visibility', models.CharField(choices=[('public_named', 'Public — named'), ('public_anonymous', 'Public — anonymous'), ('hidden', 'Hidden')], default='hidden', max_length=20)),
                ('source_encrypted', models.BinaryField(blank=True, null=True)),
                ('public_source_label', models.CharField(blank=True, default='', max_length=255)),
                ('location_visibility', models.CharField(choices=[('public_precise', 'Public — precise'), ('public_region', 'Public — region only'), ('public_country', 'Public — country only'), ('hidden', 'Hidden')], default='public_region', max_length=20)),
                ('precise_location_encrypted', models.BinaryField(blank=True, null=True)),
                ('public_location_display', models.CharField(blank=True, default='', max_length=500)),
                ('family_protected', models.BooleanField(default=True)),
                ('contact_protected', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('verification_level', models.CharField(blank=True, choices=[('level_1_reported', 'Level 1 — Reported'), ('level_2_partially_verified', 'Level 2 — Partially verified'), ('level_3_corroborated', 'Level 3 — Corroborated'), ('level_4_documented', 'Level 4 — Documented')], default='', max_length=50)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('is_exported', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translation_group', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials_created', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, help_text='Underlying Person this testimonial is built from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='cases.person')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials_published', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, help_text='Optional Report-level link (one event, one testimonial).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='cases.report')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials_submitted', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='testimonials', to='cases.testimonialtag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='testim_status_pub_idx'), models.Index(fields=['language', 'status'], name='testim_lang_status_idx'), models.Index(fields=['translation_group'], name='testim_translation_idx')],
            },
        ),
    ]
