# Generated by Django 6.0 on 2026-09-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_testimonialtag_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
