# Generated by Django 6.0 on 2026-09-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_alter_testimonial_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under review'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
