# Generated by Django 6.0 on 2026-09-15 17:02

import cases.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_alter_testimonial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=cases.storage.public_media_storage, upload_to='profiles/'),
        ),
    ]
