# Generated by Django 6.0 on 2026-09-18 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_alter_person_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('firsthand', 'Firsthand'), ('secondhand', 'Secondhand'), ('news', 'News report'), ('document', 'Document')], default='firsthand', max_length=20)),
                ('source_attribution', models.CharField(blank=True, default='', help_text='Public attribution — e.g. "family member", "BBC report"', max_length=500)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('narrative', models.TextField(blank=True, default='')),
                ('is_private', models.BooleanField(default=False, help_text='Hide this source from public reads.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='cases.report')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
