# Generated by Django 6.0 on 2026-09-18 11:24

import cases.models
import cases.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_add_source_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cases.storage.media_storage_router, upload_to=cases.models._media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'tiff', 'bmp', 'pdf', 'mp4', 'mov', 'webm']), cases.models._upload_size_validator]),
        ),
    ]
