# Generated by Django 6.0 on 2026-09-22 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_alter_familyrelationship_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreApprovedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', help_text='Why this email was pre-approved — e.g. "partner NGO contact".', max_length=255)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preapproved_emails_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pre-approved email',
                'verbose_name_plural': 'pre-approved emails',
                'ordering': ['email'],
            },
        ),
    ]
